
const cards=[...document.querySelectorAll('.product-card')],q=document.getElementById('search'),cat=document.getElementById('category'),stat=document.getElementById('status'),suggestions=document.getElementById('suggestions');
const aliases=[['едкий натр','натрій гідроокис'],['каустик','натрій гідроокис'],['уксусная кислота','оцтова кислота'],['активированный уголь','вугілля активоване'],['фильтр','фільтр'],['фильтры','фільтри'],['железо','залізо'],['натрий','натрій'],['калий','калій'],['кислота','кислота'],['гидроксид','гідроксид'],['хлорид','хлорид'],['сульфат','сульфат'],['нитрат','нітрат']];
function norm(s){return(s||'').toLowerCase().replace(/ё/g,'е').replace(/[ъь]/g,'').replace(/[(),.%®©™+]/g,' ').replace(/[-–—_/\\]/g,' ').replace(/\s+/g,' ').trim()}
function fNorm(s){return(s||'').toLowerCase().replace(/[₀₁₂₃₄₅₆₇₈₉]/g,d=>'₀₁₂₃₄₅₆₇₈₉'.indexOf(d)).replace(/[^a-z0-9]/g,'')}
function cNorm(s){return(s||'').replace(/[^0-9]/g,'')}
function variants(s){let n=norm(s),out=new Set([n]);aliases.forEach(([a,b])=>{if(n.includes(a))out.add(n.replace(a,b))});return[...out]}
function matches(c,s){if(!s)return true;const name=norm(c.dataset.name),formula=fNorm(c.dataset.formula),cas=cNorm(c.dataset.cas),fq=fNorm(s),cq=cNorm(s);if(cq.length>=3&&cas.includes(cq))return true;if(fq.length>=2&&formula.includes(fq))return true;return variants(s).some(v=>v.split(' ').every(w=>name.includes(w)))}
function render(){const s=q.value.trim(),c=cat.value,t=stat.value;let found=[];cards.forEach(x=>{const ok=matches(x,s)&&(!c||x.dataset.cat===c)&&(!t||x.dataset.status===t);x.style.display=ok?'flex':'none';if(ok&&s)found.push(x)});document.getElementById('empty').style.display=cards.some(x=>x.style.display!=='none')?'none':'block';if(!suggestions)return;if(s.length<2){suggestions.classList.remove('open');return}suggestions.innerHTML=found.slice(0,8).map(x=>{const a=x.querySelector('a[href*="product.php"]'),n=x.querySelector('h3').textContent,p=x.querySelector('strong').textContent;return`<div class="suggestion-item" data-href="${a.href}"><div><div class="suggestion-name">${n}</div><div class="suggestion-meta">${x.dataset.formula||''} · CAS ${x.dataset.cas||''}</div></div><div class="suggestion-price">${p}</div></div>`}).join('')||'<div class="suggestion-empty">Нічого не знайдено</div>';suggestions.classList.add('open');suggestions.querySelectorAll('.suggestion-item').forEach(x=>x.onclick=()=>location.href=x.dataset.href)}
q?.addEventListener('input',render);cat?.addEventListener('change',render);stat?.addEventListener('change',render);document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))suggestions?.classList.remove('open')});
